replicaCount: 1

image: lkuzmicheva/order-service

service:
  type: ClusterIP
  port: 9080
  targetPort: web

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: $1
  hosts:
    - host: arch.homework
      paths: ["/otusapp/kuzmicheva(/order/.*)"]

kafka:
  bootstrapAddress: "http://kafka.myapp.svc.cluster.local:9092"

mongo:
  uri: mongodb://mongo.myapp.svc.cluster.local:27017/ordersrv
  database: ordersrv
