server:
  port: 8082

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/paymentsrv
      database: paymentsrv
  kafka:
    bootstrap-address: localhost:9092
    group-id: payment-service-group