server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/ordersrv
      database: ordersrv
  kafka:
    bootstrap-address: localhost:9092
    group-id: order-service-group
